pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "vvovnenciuc/backup_image:latest"
        PROJECT_DIR = "${WORKSPACE}"
        DOCKER_TAG = "${params.DOCKER_TAG}"
    }
    parameters {
        string(name: 'DOCKER_TAG', defaultValue: 'latest', description: 'Tag pentru imaginea Docker')
    }
    stages {
        stage('Checkout') {
            steps {
                checkout([
                  $class: 'GitSCM',
                  branches: [[name: '*/main']],
                  userRemoteConfigs: [[url: 'https://github.com/VVovnenciuc/platforma-monitorizare.git']],
                  extensions: [[$class: 'CleanBeforeCheckout']]
            ])
            }
        }
        
        stage('Get Commit Hash') {
            steps {
                script {
                    env.GIT_COMMIT_HASH = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    echo "Git commit hash: ${env.GIT_COMMIT_HASH}"
                }
            }
        }
        
        stage('Python Lint') {
            agent {
                docker {
                    image 'python:3.11'
                    reuseNode true
                    args '-u root'
                }
            }
            steps {
                sh '''
                    pip install flake8
                    flake8 scripts
                '''
            }
        }
        
        stage('Run Tests') {
            agent {
                docker {
                    image 'python:3.11'
                    reuseNode true
                    args '-u root'
                }
            }
            steps {
                sh '''
                    pip install pytest
                    pytest -v --maxfail=1 --disable-warnings
                '''
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} -f docker/backup/Dockerfile ."
            }
        }
        
        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'credentials-dockerhub-id', 
                    usernameVariable: 'DOCKERHUB_USER', 
                    passwordVariable: 'DOCKERHUB_PASS'
                )]) {
                    // folosim script block și triple quotes pentru a evita problemele cu sh
                    script {
                        sh '''
                            #!/bin/bash
                            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

                            # Tag și push cu hash-ul commit-ului
                            docker tag ${DOCKER_IMAGE} ${DOCKERHUB_USER}/backup_image:${GIT_COMMIT_HASH}
                            docker push ${DOCKERHUB_USER}/backup_image:${GIT_COMMIT_HASH}

                            # Tag și push ca latest
                            docker tag ${DOCKER_IMAGE} ${DOCKERHUB_USER}/monitoring_image:latest
                            docker push ${DOCKERHUB_USER}/monitoring_image:latest
                            
                            docker logout
                        '''
                    }
                }
            }
        }
    }
    post {
        success {
            echo "Backup pipeline finished successfully"
        }
        failure {
            echo "Backup pipeline failed"
        }
        always {
            cleanWs()
        }
    }
}