apiVersion: apps/v1

kind: Deployment

metadata:
  name: monitoring-app
  namespace: monitoring
  labels:
    app: monitoring-app
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
        - name: monitoring
          image: vvovnenciuc/monitoring_image:latest
          env:
            - name: INTERVAL
              value: "5"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: shared-data
              mountPath: /data

        - name: backup
          image: vvovnenciuc/backup_image:latest
          env:
            - name: BACKUP_INTERVAL
              value: "5"
            - name: BACKUP_DIR
              value: "/data/backup"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi              
          volumeMounts:
            - name: shared-data
              mountPath: /data

        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html/logs
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi            
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo '<html><body><pre>' > /usr/share/nginx/html/index.html
                cat /usr/share/nginx/html/logs/system-state.log >> /usr/share/nginx/html/index.html
                echo '</pre></body></html>' >> /usr/share/nginx/html/index.html
                sleep 5
              done &
              nginx -g 'daemon off;'
      volumes:
        - name: shared-data
          emptyDir: {}
