apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: monitoring
spec:
  selector:
    app: monitoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP