apiVersion: apps/v1

kind: Deployment

metadata:
  name: monitoring-app
  namespace: default
  labels:
    app: monitoring-app
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
        - name: monitoring
          image: vvovnenciuc/monitoring_image:latest
          env:
            - name: INTERVAL
              value: "5"
          volumeMounts:
            - name: shared-data
              mountPath: /data
        - name: backup
          image: vvovnenciuc/backup_image:latest
          env:
            - name: BACKUP_INTERVAL
              value: "5"
            - name: BACKUP_DIR
              value: "/data/backup"
          volumeMounts:
            - name: shared-data
              mountPath: /data

      volumes:
        - name: shared-data