services:
  monitoring:
    build:
      context: ../
      dockerfile: docker/monitoring/Dockerfile
    container_name: monitoring_service
    environment:
      - INTERVAL=5
    volumes:
      - shared-data:/data
    restart: always

  backup:
    build:
      context: ../
      dockerfile: docker/backup/Dockerfile
    container_name: backup_service
    environment:
      - BACKUP_INTERVAL=5
      - BACKUP_DIR=/data/backup
    volumes:
      - shared-data:/data
    depends_on:
      - monitoring
    restart: always

volumes:
  shared-data: